## tstdd
version: "2.4"
services:
  nginx:
    image: nginx
    container_name: wxtile-demo-nginx
    logging:
      options:
        max-size: "2m"
        max-file: "3"
    entrypoint:
      - nginx
      - -g
      - "daemon off;"
      - -c
      - /etc/nginx/nginx.conf
    restart: always
    network_mode: bridge
    volumes:
      - ./www:/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 9292:80 # local
      # - 0.0.0.0:9292:80 # internet
